package com.messagerelay.protocol.types;

public enum ErrorCode {
    IDENTITY_IN_USE,
    ALREADY_REGISTERED,
    INVALID_MESSAGE_TYPE,
    MALFORMED_MESSAGE,
    CONNECTION_LIMIT_REACHED,
    CLIENT_LIMIT_REACHED,
    INVALID_MESSAGE
}
